// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace TechDays2013
{
	public partial class BasicControl : UIViewController
	{
		public BasicControl (IntPtr handle) : base (handle)
		{
			this.Title = "基本控制項";
            //this._switch.On = false;
		}

        public override void ViewWillAppear(bool animated)
        {
            this._switch.On = false;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            #region Hello World 按鈕
            //Hello World按鈕的click事件處理函式(1)
            this.btnHello.TouchUpInside += btnHello_TouchUpInside;

            // Hello World 按鈕的click事件處理函式(2) 匿名方法
            //this.btnHello.TouchUpInside += delegate { this.lblmsg.Text = "您已按下了Hello World"; };

            // Hello World 按鈕的click事件處理函式(3) Lambda Expression
            this.btnHello.TouchUpInside += (sender, e) => { this.lblmsg.Text = "您已按下了Hello World"; };
            #endregion

            #region Switch控制項

            this._switch.ValueChanged += (sender, e) => {
                if (this._switch.On)
                {
                    this._img.Image = UIImage.FromFile("flower.jpg");
                }
                else
                {
                    this._img.Image = null;
                }
            };

            #endregion

            #region Slider 控制項

            this._slider.ValueChanged += (sender, e) =>
            {
                this.lblmsg.Text = string.Format("滑桿目前的值為 {0}", ((int)(_slider.Value *100)).ToString());
            };

            #endregion

        }

        void btnHello_TouchUpInside(object sender, EventArgs e)
        {
            this.lblmsg.Text = "您已按下了Hello World";
        }
        
        
	}
}
