// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace TechDays2013
{
	public partial class Chart : UIViewController
	{
		public Chart (IntPtr handle) : base (handle)
		{
			this.Title = "圖表控制項";
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);
            var DestVC = (ChartDetail)segue.DestinationViewController;

            //隨機產生5筆圖表數據
            DestVC.samples = 5;

            //判斷使用者按下的圖示類型
            switch (segue.Identifier)
            { 
                case "segBar":
                    DestVC.chart = ChartType.Bar;
                    break;

                case "segCandle":
                    DestVC.chart = ChartType.Candle;
                    break;

                case "segTower":
                    DestVC.chart = ChartType.Tower;
                    break;

                case "segRadar":
                    DestVC.chart = ChartType.Radar;
                    break;

                case "segBubble":
                    DestVC.chart = ChartType.Bubble;
                    break;
            }
        }

        
	}
}
